build_from:
  amd64: "alpine:3.19"
  aarch64: "alpine:3.19"
  armv7: "alpine:3.19"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Loxone2Velux Gateway"
  org.opencontainers.image.description: "Bridge between Loxone and Velux KLF-200 for window/shutter control"
  org.opencontainers.image.source: "https://github.com/stefanbeyeler/loxone2velux"
  org.opencontainers.image.licenses: "MIT"
